spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/room_booking_system
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # safer in prod, validates schema instead of changing it
    show-sql: false

server:
  port: 8080
