server:
  port: 8081
spring:
  application:
    name: UniversityRoomBookingSystem
  profiles:
    active: dev

logging:
  level:
    root: INFO
    com.sprints.UniversityRoomBookingSystem: DEBUG
  file:
    name: app.log
